apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pstoihp80-nodejs 
  janus-idp.io/tekton: pstoihp80-nodejs
  backstage.io/kubernetes-id: pstoihp80-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pstoihp80-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  